# Generated by Django 4.2.3 on 2024-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0005_alter_attendancerecord_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours_worked',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
