# Generated by Django 4.2.3 on 2024-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0006_alter_attendancerecord_total_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours_worked',
            field=models.DurationField(blank=True, max_length=6, null=True),
        ),
    ]
