# Generated by Django 4.2.3 on 2024-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0008_alter_attendancerecord_total_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='first_login',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='last_logout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours_worked',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
