# Generated by Django 4.2.3 on 2024-08-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0010_alter_attendancerecord_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
