# Generated by Django 4.2.3 on 2024-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0011_alter_attendancerecord_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='last_logout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
