# Generated by Django 4.2.3 on 2024-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0012_alter_attendancerecord_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
