# Generated by Django 4.2.3 on 2024-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0013_attendancerecord_is_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
