# Generated by Django 4.2.3 on 2024-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0014_alter_attendancerecord_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='first_login',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
