# Generated by Django 5.1 on 2024-09-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaTimeSync', '0017_attendancerecord_expected_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='expected_hours',
            field=models.IntegerField(default=8),
        ),
    ]
